name: Generate Image List

on:
  push:
    paths:
      - 'width/**'
      - 'length/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate width.json
        run: |
          BASE_URL="https://iyusei02-lgtm.github.io/images"
          
          if [ -d "width" ]; then
            find width -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | \
            sed "s|^|${BASE_URL}/|" | \
            jq -R -s -c 'split("\n")[:-1]' > width.json
          else
            echo "[]" > width.json
          fi
          
      - name: Generate length.json
        run: |
          BASE_URL="https://iyusei02-lgtm.github.io/images"
          
          if [ -d "length" ]; then
            find length -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | \
            sed "s|^|${BASE_URL}/|" | \
            jq -R -s -c 'split("\n")[:-1]' > length.json
          else
            echo "[]" > length.json
          fi
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add width.json length.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update image lists [skip ci]" && git push)
