name: Generate Image List

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate image list JSON with full URLs
        run: |
          # username과 repo-name을 본인 것으로 변경하세요
          BASE_URL="https://iyusei02-lgtm.github.io/images"
          
          find images -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | \
          sed "s|^|${BASE_URL}/|" | \
          jq -R -s -c 'split("\n")[:-1]' > images.json
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update image list [skip ci]" && git push)
